# SAE checkpoint to load (required)
sae_checkpoint:
  experiment: "layer_sweeps"
  timestamp: "Jan19-20-09"  # Format: %b%d-%H-%M from training
  # Will load: experiments/${experiment}/${timestamp}/model.pth
  # And config: experiments/${experiment}/${timestamp}/.hydra/config.yaml

# Analysis parameters
analysis:
  # Enable/disable analysis types
  run_label_scoring: true
  run_gene_scoring: false
  run_expression_scoring: false
  run_density_scoring: false
  
  # Parameters for each analysis type
  label_scoring:
    label: ["celltype"]
    score: ["AMI"]
  gene_scoring:
    sets: ["GO"]
    families: ["ribosomal", "mitochondrial", "HLA"]
    threshold: 0.5
  expression_scoring:
    score: ["std", "mean"]
    threshold: 0.5
  density_scoring:
    threshold: 0.1



hydra:
  job:
    chdir: False 
  run:
    dir: experiments/analysis/${sae_checkpoint.experiment}/
  job_logging:
    handlers:
      file:
        filename: ${hydra.run.dir}/run.log