defaults:
  - data: pancreas

seed: 0

experiments:
  - number: "steering_tables"
    date: "Jan19-08-44"
    seeds: [42, 43, 44]
    clamps: [-2.0]
    n_features: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
    selector: [AMI, random]
    original: false

comparison_id: 'randomvsAMI_pancreas'

hydra:
  job:
    chdir: False
  run:
    dir: experiments/benchmark/${comparison_id}/