# SAE checkpoint to load (required)
sae_checkpoint:
  experiment: "layer_sweeps"  # Experiment name
  timestamp: "Jan19-20-09"  # Format: %b%d-%H-%M from training
  # Will load: experiments/${experiment}/${timestamp}/model.pth
  # And config: experiments/${experiment}/${timestamp}/.hydra/config.yaml


hydra:
  job:
    chdir: False 
  run:
    dir: cached_features/${sae_checkpoint.experiment}/
  job_logging:
    handlers:
      file:
        filename: ${hydra.run.dir}/run.log